name: Continues Export

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  ContinuesExport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run Continues Example
      run: cd example/continues_export && go build -v ./... && ./continues_export -total 10
